---
- name: "Setup Cobbler profile using cobblerTool inside Vagrant VM"
  become: true
  become_method: sudo
  command:
    cmd: "cobblerTool {{ target_os }} --repo_dir /vagrant_shared/config/systems --pconfig {{ config_json }} --force --debug"
  register: cobbler_output
  delegate_to: localhost

- debug:
    msg: "Running cobblerToolWrapper.sh with parameters: {{ target_os }}, --repo_dir /vagrant_shared/config/systems, --pconfig {{ config_json }}, --force, --debug"
  when: debug_mode | default(false)
  delegate_to: localhost

- debug:
    msg: "Output from cobblerToolWrapper.sh: {{ cobbler_output.stdout }}"
    verbosity: 2
  when: debug_mode | default(false)
  delegate_to: localhost

# "/vagrant_shared/ansible/utils/cobblerToolWrapper.sh {{ item }} --repo_dir /vagrant_shared/config/systems --pconfig {{ pconfig }} --force --debug"