---
- name: Turn iBoot On
  iboot-on:
    ip: "{{ ib_ip }}"
    user: "{{ ib_user }}"
    password: "{{ ib_password }}"
  delegate_to: localhost
  when: ib_action == 'on'

- name: Turn iBoot Off
  iboot-off:
    ip: "{{ ib_ip }}"
    user: "{{ ib_user }}"
    password: "{{ ib_password }}"
  delegate_to: localhost
  when: ib_action == 'off'
