# -*- mode: ruby -*-
# vi: set ft=ruby :

cobbler_network = "ASIX AX88179 USB 3.0 to Gigabit Ethernet Adapter"
main_network = "Intel(R) Ethernet Connection (10) I219-V"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true

  config.vm.network "public_network", bridge: main_network
  config.vm.network "public_network", bridge: cobbler_network, ip: "192.168.75.1"

  folders_to_sync = [
    ["./shared", "/vagrant_shared"],
    ["../scripts", "/vagrant_shared/scripts"],
    ["../docker", "/vagrant_shared/docker"],
    ["../docker/cobbler/volumes", "/vagrant_shared/docker/volumes"],
    ["../squid", "/vagrant_shared/squid"]
  ]
  
  folders_to_sync.each do |src, dest|
    config.vm.synced_folder src, dest, type: "rsync", rsync__exclude: ".git/"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "test-automation vm"
  end

  config.vm.provision "shell", path: "../scripts/provision_vagrant_vm.sh"
end