---
- name: Extract kernel version
  shell: uname -r
  register: kernel_version

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ yum_generic_packages }}"
  environment:
    http_proxy: "http://{{ gateway }}:3128"
    https_proxy: "http://{{ gateway }}:3128"
  ignore_errors: true