---
- name: Assert required variables are defined
  assert:
    that:
      - iboot_ip is defined
      - iboot_user is defined
      - iboot_password is defined
      - device_ip_address is defined
    fail_msg: "Required variable(s) are not defined"

- name: Power off the device using iBoot
  include_role:
    name: system-operations/iboot-control
  vars:
    ib_action: 'off'
    ib_ip: "{{ iboot_ip }}"
    ib_user: "{{ iboot_user }}"
    ib_password: "{{ iboot_password }}"

- name: Wait for a defined interval
  pause:
    seconds: "{{ power_cycle_pause | default(10) }}"

- name: Power on the device using iBoot
  include_role:
    name: system-operations/iboot-control
  vars:
    ib_action: 'on'
    ib_ip: "{{ iboot_ip }}"
    ib_user: "{{ iboot_user }}"
    ib_password: "{{ iboot_password }}"

- name: Wait for the device to come back online
  wait_for:
    host: "{{ device_ip_address }}"
    port: "{{ ssh_port | default(22) }}"
    state: started
    delay: "{{ ssh_delay | default(10) }}"
    timeout: "{{ ssh_timeout | default(1200) }}"
  delegate_to: localhost
  register: result

- name: Handle timeout error
  fail:
    msg: "The device did not come back online within the specified timeout period."
  when: result.failed