---
- hosts: "{{ pconfig_vars.ip_address }}"
  gather_facts: false
  remote_user: "{{ pconfig_vars.dev_username }}"
  vars:
    ansible_ssh_pass: "{{ pconfig_vars.dev_password }}"
  tasks:
    - name: Execute command on target board
      command: 
        cmd: "{{ command_to_run }}"
      register: command_output