- name: Check if cobblerToolWrapper.sh exists
  stat:
    path: /vagrant_shared/ansible/utils/cobblerToolWrapper.sh
  register: result
  delegate_to: localhost

- debug:
    msg: "File exists"
  when: result.stat.exists
  delegate_to: localhost

- name: "Setup Cobbler profile using cobblerTool inside Vagrant VM"
  become: true
  become_method: sudo
  command:
    cmd: "/vagrant_shared/ansible/utils/cobblerToolWrapper.sh {{ item }} --repo_dir /vagrant_shared/config/systems --pconfig /vagrant_shared/config/systems/{{ pconfig }} --force --debug"
  register: cobbler_output
  delegate_to: localhost