---
- name: Conditionally gather facts
  setup:
  when: ansible_os_family is undefined

- name: Ensure [main] section exists in dnf.conf
  when: ansible_os_family == "RedHat"
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^\[main\]'
    line: '[main]'
    create: true
  become: true

- name: Set up proxy for DNF (Recent RedHat based systems)
  when: ansible_os_family == "RedHat"
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^proxy='
    line: "proxy={{ proxy_proto }}://{{ proxy_host }}:{{ proxy_port }}"
    create: true
  become: true

- name: Set up proxy for APT (Debian based systems)
  when: ansible_os_family == "Debian"
  copy:
    content: |
      Acquire::http::Proxy "{{ proxy_proto }}://{{ proxy_host }}:{{ proxy_port }}";
    dest: /etc/apt/apt.conf.d/90proxy
  become: true

- name: Set up proxy for bash environment
  lineinfile:
    path: /etc/environment
    regexp: '^{{ item }}_proxy='
    line: "{{ item }}_proxy={{ proxy_proto }}://{{ proxy_host }}:{{ proxy_port }}"
    state: present
  loop:
    - http
    - https
  become: true

- name: Apply the proxy settings immediately
  shell: source /etc/environment
  become: true
- name: Apply the proxy settings immediately
  shell: |
    export HTTP_PROXY="{{ proxy_proto }}://{{ proxy_host }}:{{ proxy_port }}"
    export HTTPS_PROXY="{{ proxy_proto }}://{{ proxy_host }}:{{ proxy_port }}"

- name: Test the proxy setup
  command: curl -I http://www.google.com
  register: test_result
  ignore_errors: true
  when: debug_mode | default (false)

- name: Display proxy test result
  debug:
    msg: "{{ test_result }}"
  when: debug_mode | default (false)
