- name: Ensure DNF is updated
  dnf:
    name: '*'
    state: latest
  become: true
  register: dnf_result

- name: Reboot the system if necessary
  reboot:
    msg: "Rebooting due to system update"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - ansible_os_family == "RedHat"
    - dnf_result.changed
  become: true
