- name: Include distribution-specific variables
  include_vars: "{{ found_file }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_version | lower }}.yaml"
    - "{{ ansible_distribution | lower }}.yaml"
  register: included_vars
  loop_control:
    loop_var: found_file


- name: Debug | Print included distribution-specific variables
  debug:
    msg: "Included vars file: {{ included_vars.results[0].ansible_included_var_files }}"
  when: 
    - included_vars.results[0].ansible_included_var_files is defined
    - debug_mode | default(false)

- name: Include common Fedora variables
  include_vars: "vars/fedora.yaml"
  register: fedora_vars

- name: Debug | Print common Fedora variables
  debug:
    var: fedora_vars
  when: debug_mode | default(false)

- name: Install common Fedora packages
  dnf:
    name: "{{ common_fedora_packages }}"
    state: present
  become: true
  register: yum_result

- name: Install distribution-specific packages
  dnf:
    name: "{{ included_vars.results[0].ansible_facts.specific_fedora36_packages }}"
    state: present
  when: included_vars.results[0].ansible_facts.specific_fedora36_packages is defined
  become: true
  register: specific_yum_result

- name: Debug | Print specific dnf installation result
  debug:
    var: specific_yum_result
  when: debug_mode | default(false)

- name: Debug | Print dnf installation result
  debug:
    var: yum_result
  when: debug_mode | default(false)

- name: Include dnf-update tasks
  include_tasks: "{{ role_path }}/tasks/dnf-update.yaml"
  register: yum_update_result

- name: Debug | Print dnf-update tasks result
  debug:
    var: yum_update_result
  when: debug_mode | default(false)

- name: Include dnf-generic tasks
  include_tasks: "{{ role_path }}/tasks/generic_packages.yaml"
  register: yum_generic_result

- name: Debug | Print dnf-generic tasks result
  debug:
    var: yum_generic_result
  when: debug_mode | default(false)
