---
- name: Conditionally gather facts
  setup:
  when: ansible_os_family is undefined

- name: System update
  include_tasks: "system-update.yaml"

- set_fact:
    supported_families:
      - redhat

- block:
    - name: Install dependencies based on OS family
      include_tasks: "{{ ansible_os_family | lower }}.yaml"
      when: ansible_os_family | lower in supported_families | map('lower') | list
  become: false


# To Add Support for a New OS Family:
# 1. Extend `supported_families` with the new family name.
# 2. Duplicate and rename `redhat.yaml` for the new family, e.g., `debian.yaml`.
# 3. Adjust tasks and variables in the new family file as needed.
# 4. In `vars/`, create `<family>-packages.yaml` for common packages, and optionally specific files like `debian10.yaml`.
