- name: Ensure the system packages are updated
  package:
    name: '*'
    state: latest
  become: true
  register: pkg_result

- name: Reboot the system if necessary
  reboot:
    msg: "Rebooting due to system update"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: pkg_result.changed
  become: true

