---
- name: "Test Framework Playbook"
  hosts: localhost
  gather_facts: no
  vars:
    board_name: "xvr19"
    required_os: []
    test_metadata: []

  vars_files:
    - "/vagrant_shared/config/systems/{{ board_name }}.json"

  tasks:
    - name: Fetch metadata for each test
      include_tasks: fetch-metadata.yaml
      with_items: "{{ tests }}"
      loop_control:
        loop_var: current_test

    - name: Retrieve the Operating Systems required for testing
      include_tasks: fetch-os-required.yaml

    - name: Execute OS-specific tasks and tests
      include_tasks: os-tasks.yaml
      with_items: "{{ required_os | unique }}"
      loop_control:
        loop_var: current_os

    - name: Add target IP to inventory
      add_host:
        name: "{{ ip_address }}"
        groups: target_board
        ansible_ssh_user: "{{ dev_username }}"
        ansible_ssh_pass: "{{ dev_password }}"

- name: Execute OS-specific tasks and tests on board
  hosts: target_board
  gather_facts: no

  tasks:
    - name: Execute OS-tasks for each required OS
      include_tasks: os-tasks.yaml
      with_items: "{{ required_os | unique }}"
      loop_control:
        loop_var: current_os
